// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	bodyweight "github.com/vladgrskkh/onerep-api/internal/domain/bodyweight"

	mock "github.com/stretchr/testify/mock"

	servicebodyweight "github.com/vladgrskkh/onerep-api/internal/service/bodyweight"

	time "time"

	uuid "github.com/google/uuid"
)

// MockBodyWeightService is an autogenerated mock type for the BodyWeightService type
type MockBodyWeightService struct {
	mock.Mock
}

type MockBodyWeightService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBodyWeightService) EXPECT() *MockBodyWeightService_Expecter {
	return &MockBodyWeightService_Expecter{mock: &_m.Mock}
}

// ListBodyWeight provides a mock function with given fields: ctx, userID, since
func (_m *MockBodyWeightService) ListBodyWeight(ctx context.Context, userID uuid.UUID, since time.Time) ([]*bodyweight.BodyWeight, error) {
	ret := _m.Called(ctx, userID, since)

	if len(ret) == 0 {
		panic("no return value specified for ListBodyWeight")
	}

	var r0 []*bodyweight.BodyWeight
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) ([]*bodyweight.BodyWeight, error)); ok {
		return rf(ctx, userID, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) []*bodyweight.BodyWeight); ok {
		r0 = rf(ctx, userID, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*bodyweight.BodyWeight)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, userID, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBodyWeightService_ListBodyWeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBodyWeight'
type MockBodyWeightService_ListBodyWeight_Call struct {
	*mock.Call
}

// ListBodyWeight is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - since time.Time
func (_e *MockBodyWeightService_Expecter) ListBodyWeight(ctx interface{}, userID interface{}, since interface{}) *MockBodyWeightService_ListBodyWeight_Call {
	return &MockBodyWeightService_ListBodyWeight_Call{Call: _e.mock.On("ListBodyWeight", ctx, userID, since)}
}

func (_c *MockBodyWeightService_ListBodyWeight_Call) Run(run func(ctx context.Context, userID uuid.UUID, since time.Time)) *MockBodyWeightService_ListBodyWeight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockBodyWeightService_ListBodyWeight_Call) Return(_a0 []*bodyweight.BodyWeight, _a1 error) *MockBodyWeightService_ListBodyWeight_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBodyWeightService_ListBodyWeight_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) ([]*bodyweight.BodyWeight, error)) *MockBodyWeightService_ListBodyWeight_Call {
	_c.Call.Return(run)
	return _c
}

// LogBodyWeight provides a mock function with given fields: ctx, cmd
func (_m *MockBodyWeightService) LogBodyWeight(ctx context.Context, cmd servicebodyweight.LogBodyWeightCommand) (*bodyweight.BodyWeight, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for LogBodyWeight")
	}

	var r0 *bodyweight.BodyWeight
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, servicebodyweight.LogBodyWeightCommand) (*bodyweight.BodyWeight, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, servicebodyweight.LogBodyWeightCommand) *bodyweight.BodyWeight); ok {
		r0 = rf(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bodyweight.BodyWeight)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, servicebodyweight.LogBodyWeightCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBodyWeightService_LogBodyWeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogBodyWeight'
type MockBodyWeightService_LogBodyWeight_Call struct {
	*mock.Call
}

// LogBodyWeight is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd servicebodyweight.LogBodyWeightCommand
func (_e *MockBodyWeightService_Expecter) LogBodyWeight(ctx interface{}, cmd interface{}) *MockBodyWeightService_LogBodyWeight_Call {
	return &MockBodyWeightService_LogBodyWeight_Call{Call: _e.mock.On("LogBodyWeight", ctx, cmd)}
}

func (_c *MockBodyWeightService_LogBodyWeight_Call) Run(run func(ctx context.Context, cmd servicebodyweight.LogBodyWeightCommand)) *MockBodyWeightService_LogBodyWeight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(servicebodyweight.LogBodyWeightCommand))
	})
	return _c
}

func (_c *MockBodyWeightService_LogBodyWeight_Call) Return(_a0 *bodyweight.BodyWeight, _a1 error) *MockBodyWeightService_LogBodyWeight_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBodyWeightService_LogBodyWeight_Call) RunAndReturn(run func(context.Context, servicebodyweight.LogBodyWeightCommand) (*bodyweight.BodyWeight, error)) *MockBodyWeightService_LogBodyWeight_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBodyWeightService creates a new instance of MockBodyWeightService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBodyWeightService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBodyWeightService {
	mock := &MockBodyWeightService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
