// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	progress "github.com/vladgrskkh/onerep-api/internal/domain/progress"

	time "time"

	uuid "github.com/google/uuid"
)

// MockProgressService is an autogenerated mock type for the ProgressService type
type MockProgressService struct {
	mock.Mock
}

type MockProgressService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProgressService) EXPECT() *MockProgressService_Expecter {
	return &MockProgressService_Expecter{mock: &_m.Mock}
}

// Get1RM provides a mock function with given fields: ctx, userID, exerciseID, from, to
func (_m *MockProgressService) Get1RM(ctx context.Context, userID uuid.UUID, exerciseID uuid.UUID, from *time.Time, to *time.Time) ([]progress.Progress1RM, error) {
	ret := _m.Called(ctx, userID, exerciseID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for Get1RM")
	}

	var r0 []progress.Progress1RM
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *time.Time, *time.Time) ([]progress.Progress1RM, error)); ok {
		return rf(ctx, userID, exerciseID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *time.Time, *time.Time) []progress.Progress1RM); ok {
		r0 = rf(ctx, userID, exerciseID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]progress.Progress1RM)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, *time.Time, *time.Time) error); ok {
		r1 = rf(ctx, userID, exerciseID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProgressService_Get1RM_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get1RM'
type MockProgressService_Get1RM_Call struct {
	*mock.Call
}

// Get1RM is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - exerciseID uuid.UUID
//   - from *time.Time
//   - to *time.Time
func (_e *MockProgressService_Expecter) Get1RM(ctx interface{}, userID interface{}, exerciseID interface{}, from interface{}, to interface{}) *MockProgressService_Get1RM_Call {
	return &MockProgressService_Get1RM_Call{Call: _e.mock.On("Get1RM", ctx, userID, exerciseID, from, to)}
}

func (_c *MockProgressService_Get1RM_Call) Run(run func(ctx context.Context, userID uuid.UUID, exerciseID uuid.UUID, from *time.Time, to *time.Time)) *MockProgressService_Get1RM_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(*time.Time), args[4].(*time.Time))
	})
	return _c
}

func (_c *MockProgressService_Get1RM_Call) Return(_a0 []progress.Progress1RM, _a1 error) *MockProgressService_Get1RM_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProgressService_Get1RM_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, *time.Time, *time.Time) ([]progress.Progress1RM, error)) *MockProgressService_Get1RM_Call {
	_c.Call.Return(run)
	return _c
}

// GetVolume provides a mock function with given fields: ctx, userID, from, to
func (_m *MockProgressService) GetVolume(ctx context.Context, userID uuid.UUID, from *time.Time, to *time.Time) ([]progress.ProgressVolume, error) {
	ret := _m.Called(ctx, userID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetVolume")
	}

	var r0 []progress.ProgressVolume
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *time.Time, *time.Time) ([]progress.ProgressVolume, error)); ok {
		return rf(ctx, userID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *time.Time, *time.Time) []progress.ProgressVolume); ok {
		r0 = rf(ctx, userID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]progress.ProgressVolume)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *time.Time, *time.Time) error); ok {
		r1 = rf(ctx, userID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProgressService_GetVolume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVolume'
type MockProgressService_GetVolume_Call struct {
	*mock.Call
}

// GetVolume is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - from *time.Time
//   - to *time.Time
func (_e *MockProgressService_Expecter) GetVolume(ctx interface{}, userID interface{}, from interface{}, to interface{}) *MockProgressService_GetVolume_Call {
	return &MockProgressService_GetVolume_Call{Call: _e.mock.On("GetVolume", ctx, userID, from, to)}
}

func (_c *MockProgressService_GetVolume_Call) Run(run func(ctx context.Context, userID uuid.UUID, from *time.Time, to *time.Time)) *MockProgressService_GetVolume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*time.Time), args[3].(*time.Time))
	})
	return _c
}

func (_c *MockProgressService_GetVolume_Call) Return(_a0 []progress.ProgressVolume, _a1 error) *MockProgressService_GetVolume_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProgressService_GetVolume_Call) RunAndReturn(run func(context.Context, uuid.UUID, *time.Time, *time.Time) ([]progress.ProgressVolume, error)) *MockProgressService_GetVolume_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProgressService creates a new instance of MockProgressService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProgressService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProgressService {
	mock := &MockProgressService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
