// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	progress "github.com/vladgrskkh/onerep-api/internal/domain/progress"

	uuid "github.com/google/uuid"
)

// MockProgressRepository is an autogenerated mock type for the ProgressRepository type
type MockProgressRepository struct {
	mock.Mock
}

type MockProgressRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProgressRepository) EXPECT() *MockProgressRepository_Expecter {
	return &MockProgressRepository_Expecter{mock: &_m.Mock}
}

// GetBest1RM provides a mock function with given fields: ctx, exerciseID, userID
func (_m *MockProgressRepository) GetBest1RM(ctx context.Context, exerciseID uuid.UUID, userID uuid.UUID) (float64, error) {
	ret := _m.Called(ctx, exerciseID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBest1RM")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (float64, error)); ok {
		return rf(ctx, exerciseID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) float64); ok {
		r0 = rf(ctx, exerciseID, userID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, exerciseID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProgressRepository_GetBest1RM_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBest1RM'
type MockProgressRepository_GetBest1RM_Call struct {
	*mock.Call
}

// GetBest1RM is a helper method to define mock.On call
//   - ctx context.Context
//   - exerciseID uuid.UUID
//   - userID uuid.UUID
func (_e *MockProgressRepository_Expecter) GetBest1RM(ctx interface{}, exerciseID interface{}, userID interface{}) *MockProgressRepository_GetBest1RM_Call {
	return &MockProgressRepository_GetBest1RM_Call{Call: _e.mock.On("GetBest1RM", ctx, exerciseID, userID)}
}

func (_c *MockProgressRepository_GetBest1RM_Call) Run(run func(ctx context.Context, exerciseID uuid.UUID, userID uuid.UUID)) *MockProgressRepository_GetBest1RM_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockProgressRepository_GetBest1RM_Call) Return(_a0 float64, _a1 error) *MockProgressRepository_GetBest1RM_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProgressRepository_GetBest1RM_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (float64, error)) *MockProgressRepository_GetBest1RM_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert1RM provides a mock function with given fields: ctx, p
func (_m *MockProgressRepository) Upsert1RM(ctx context.Context, p progress.Progress1RM) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Upsert1RM")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, progress.Progress1RM) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProgressRepository_Upsert1RM_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert1RM'
type MockProgressRepository_Upsert1RM_Call struct {
	*mock.Call
}

// Upsert1RM is a helper method to define mock.On call
//   - ctx context.Context
//   - p progress.Progress1RM
func (_e *MockProgressRepository_Expecter) Upsert1RM(ctx interface{}, p interface{}) *MockProgressRepository_Upsert1RM_Call {
	return &MockProgressRepository_Upsert1RM_Call{Call: _e.mock.On("Upsert1RM", ctx, p)}
}

func (_c *MockProgressRepository_Upsert1RM_Call) Run(run func(ctx context.Context, p progress.Progress1RM)) *MockProgressRepository_Upsert1RM_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(progress.Progress1RM))
	})
	return _c
}

func (_c *MockProgressRepository_Upsert1RM_Call) Return(_a0 error) *MockProgressRepository_Upsert1RM_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProgressRepository_Upsert1RM_Call) RunAndReturn(run func(context.Context, progress.Progress1RM) error) *MockProgressRepository_Upsert1RM_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProgressRepository creates a new instance of MockProgressRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProgressRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProgressRepository {
	mock := &MockProgressRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
