// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	template "github.com/vladgrskkh/onerep-api/internal/domain/template"

	uuid "github.com/google/uuid"
)

// MockTemplateRepository is an autogenerated mock type for the TemplateRepository type
type MockTemplateRepository struct {
	mock.Mock
}

type MockTemplateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTemplateRepository) EXPECT() *MockTemplateRepository_Expecter {
	return &MockTemplateRepository_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockTemplateRepository) FindByID(ctx context.Context, id uuid.UUID) (*template.Template, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *template.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*template.Template, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *template.Template); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*template.Template)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTemplateRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockTemplateRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTemplateRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockTemplateRepository_FindByID_Call {
	return &MockTemplateRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockTemplateRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTemplateRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTemplateRepository_FindByID_Call) Return(_a0 *template.Template, _a1 error) *MockTemplateRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTemplateRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*template.Template, error)) *MockTemplateRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTemplateRepository creates a new instance of MockTemplateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTemplateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTemplateRepository {
	mock := &MockTemplateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
