// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	workout "github.com/vladgrskkh/onerep-api/internal/domain/workout"
)

// MockVolumeQueue is an autogenerated mock type for the VolumeQueue type
type MockVolumeQueue struct {
	mock.Mock
}

type MockVolumeQueue_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVolumeQueue) EXPECT() *MockVolumeQueue_Expecter {
	return &MockVolumeQueue_Expecter{mock: &_m.Mock}
}

// EnqueueVolumeCalc provides a mock function with given fields: ctx, _a1
func (_m *MockVolumeQueue) EnqueueVolumeCalc(ctx context.Context, _a1 workout.Workout) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueVolumeCalc")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, workout.Workout) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVolumeQueue_EnqueueVolumeCalc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueVolumeCalc'
type MockVolumeQueue_EnqueueVolumeCalc_Call struct {
	*mock.Call
}

// EnqueueVolumeCalc is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 workout.Workout
func (_e *MockVolumeQueue_Expecter) EnqueueVolumeCalc(ctx interface{}, _a1 interface{}) *MockVolumeQueue_EnqueueVolumeCalc_Call {
	return &MockVolumeQueue_EnqueueVolumeCalc_Call{Call: _e.mock.On("EnqueueVolumeCalc", ctx, _a1)}
}

func (_c *MockVolumeQueue_EnqueueVolumeCalc_Call) Run(run func(ctx context.Context, _a1 workout.Workout)) *MockVolumeQueue_EnqueueVolumeCalc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(workout.Workout))
	})
	return _c
}

func (_c *MockVolumeQueue_EnqueueVolumeCalc_Call) Return(_a0 error) *MockVolumeQueue_EnqueueVolumeCalc_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVolumeQueue_EnqueueVolumeCalc_Call) RunAndReturn(run func(context.Context, workout.Workout) error) *MockVolumeQueue_EnqueueVolumeCalc_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVolumeQueue creates a new instance of MockVolumeQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVolumeQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVolumeQueue {
	mock := &MockVolumeQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
