// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"

	workout "github.com/vladgrskkh/onerep-api/internal/domain/workout"
)

// MockWorkoutRepository is an autogenerated mock type for the WorkoutRepository type
type MockWorkoutRepository struct {
	mock.Mock
}

type MockWorkoutRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkoutRepository) EXPECT() *MockWorkoutRepository_Expecter {
	return &MockWorkoutRepository_Expecter{mock: &_m.Mock}
}

// AddExercise provides a mock function with given fields: ctx, workoutID, exerciseID
func (_m *MockWorkoutRepository) AddExercise(ctx context.Context, workoutID uuid.UUID, exerciseID uuid.UUID) (workout.WorkoutExercise, error) {
	ret := _m.Called(ctx, workoutID, exerciseID)

	if len(ret) == 0 {
		panic("no return value specified for AddExercise")
	}

	var r0 workout.WorkoutExercise
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (workout.WorkoutExercise, error)); ok {
		return rf(ctx, workoutID, exerciseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) workout.WorkoutExercise); ok {
		r0 = rf(ctx, workoutID, exerciseID)
	} else {
		r0 = ret.Get(0).(workout.WorkoutExercise)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, workoutID, exerciseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkoutRepository_AddExercise_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddExercise'
type MockWorkoutRepository_AddExercise_Call struct {
	*mock.Call
}

// AddExercise is a helper method to define mock.On call
//   - ctx context.Context
//   - workoutID uuid.UUID
//   - exerciseID uuid.UUID
func (_e *MockWorkoutRepository_Expecter) AddExercise(ctx interface{}, workoutID interface{}, exerciseID interface{}) *MockWorkoutRepository_AddExercise_Call {
	return &MockWorkoutRepository_AddExercise_Call{Call: _e.mock.On("AddExercise", ctx, workoutID, exerciseID)}
}

func (_c *MockWorkoutRepository_AddExercise_Call) Run(run func(ctx context.Context, workoutID uuid.UUID, exerciseID uuid.UUID)) *MockWorkoutRepository_AddExercise_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockWorkoutRepository_AddExercise_Call) Return(_a0 workout.WorkoutExercise, _a1 error) *MockWorkoutRepository_AddExercise_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkoutRepository_AddExercise_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (workout.WorkoutExercise, error)) *MockWorkoutRepository_AddExercise_Call {
	_c.Call.Return(run)
	return _c
}

// BatchInsertExercises provides a mock function with given fields: ctx, exercises
func (_m *MockWorkoutRepository) BatchInsertExercises(ctx context.Context, exercises []workout.WorkoutExercise) error {
	ret := _m.Called(ctx, exercises)

	if len(ret) == 0 {
		panic("no return value specified for BatchInsertExercises")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []workout.WorkoutExercise) error); ok {
		r0 = rf(ctx, exercises)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWorkoutRepository_BatchInsertExercises_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchInsertExercises'
type MockWorkoutRepository_BatchInsertExercises_Call struct {
	*mock.Call
}

// BatchInsertExercises is a helper method to define mock.On call
//   - ctx context.Context
//   - exercises []workout.WorkoutExercise
func (_e *MockWorkoutRepository_Expecter) BatchInsertExercises(ctx interface{}, exercises interface{}) *MockWorkoutRepository_BatchInsertExercises_Call {
	return &MockWorkoutRepository_BatchInsertExercises_Call{Call: _e.mock.On("BatchInsertExercises", ctx, exercises)}
}

func (_c *MockWorkoutRepository_BatchInsertExercises_Call) Run(run func(ctx context.Context, exercises []workout.WorkoutExercise)) *MockWorkoutRepository_BatchInsertExercises_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]workout.WorkoutExercise))
	})
	return _c
}

func (_c *MockWorkoutRepository_BatchInsertExercises_Call) Return(_a0 error) *MockWorkoutRepository_BatchInsertExercises_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWorkoutRepository_BatchInsertExercises_Call) RunAndReturn(run func(context.Context, []workout.WorkoutExercise) error) *MockWorkoutRepository_BatchInsertExercises_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, w
func (_m *MockWorkoutRepository) Create(ctx context.Context, w workout.Workout) (workout.Workout, error) {
	ret := _m.Called(ctx, w)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 workout.Workout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, workout.Workout) (workout.Workout, error)); ok {
		return rf(ctx, w)
	}
	if rf, ok := ret.Get(0).(func(context.Context, workout.Workout) workout.Workout); ok {
		r0 = rf(ctx, w)
	} else {
		r0 = ret.Get(0).(workout.Workout)
	}

	if rf, ok := ret.Get(1).(func(context.Context, workout.Workout) error); ok {
		r1 = rf(ctx, w)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkoutRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockWorkoutRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - w workout.Workout
func (_e *MockWorkoutRepository_Expecter) Create(ctx interface{}, w interface{}) *MockWorkoutRepository_Create_Call {
	return &MockWorkoutRepository_Create_Call{Call: _e.mock.On("Create", ctx, w)}
}

func (_c *MockWorkoutRepository_Create_Call) Run(run func(ctx context.Context, w workout.Workout)) *MockWorkoutRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(workout.Workout))
	})
	return _c
}

func (_c *MockWorkoutRepository_Create_Call) Return(_a0 workout.Workout, _a1 error) *MockWorkoutRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkoutRepository_Create_Call) RunAndReturn(run func(context.Context, workout.Workout) (workout.Workout, error)) *MockWorkoutRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockWorkoutRepository) FindByID(ctx context.Context, id uuid.UUID) (workout.Workout, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 workout.Workout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (workout.Workout, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) workout.Workout); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(workout.Workout)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkoutRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockWorkoutRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockWorkoutRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockWorkoutRepository_FindByID_Call {
	return &MockWorkoutRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockWorkoutRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockWorkoutRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockWorkoutRepository_FindByID_Call) Return(_a0 workout.Workout, _a1 error) *MockWorkoutRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkoutRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (workout.Workout, error)) *MockWorkoutRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Finish provides a mock function with given fields: ctx, id, finishedAt
func (_m *MockWorkoutRepository) Finish(ctx context.Context, id uuid.UUID, finishedAt time.Time) (workout.Workout, error) {
	ret := _m.Called(ctx, id, finishedAt)

	if len(ret) == 0 {
		panic("no return value specified for Finish")
	}

	var r0 workout.Workout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) (workout.Workout, error)); ok {
		return rf(ctx, id, finishedAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) workout.Workout); ok {
		r0 = rf(ctx, id, finishedAt)
	} else {
		r0 = ret.Get(0).(workout.Workout)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, id, finishedAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkoutRepository_Finish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Finish'
type MockWorkoutRepository_Finish_Call struct {
	*mock.Call
}

// Finish is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - finishedAt time.Time
func (_e *MockWorkoutRepository_Expecter) Finish(ctx interface{}, id interface{}, finishedAt interface{}) *MockWorkoutRepository_Finish_Call {
	return &MockWorkoutRepository_Finish_Call{Call: _e.mock.On("Finish", ctx, id, finishedAt)}
}

func (_c *MockWorkoutRepository_Finish_Call) Run(run func(ctx context.Context, id uuid.UUID, finishedAt time.Time)) *MockWorkoutRepository_Finish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockWorkoutRepository_Finish_Call) Return(_a0 workout.Workout, _a1 error) *MockWorkoutRepository_Finish_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkoutRepository_Finish_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) (workout.Workout, error)) *MockWorkoutRepository_Finish_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockWorkoutRepository) List(ctx context.Context, filter workout.WorkoutFilter) ([]workout.Workout, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []workout.Workout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, workout.WorkoutFilter) ([]workout.Workout, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, workout.WorkoutFilter) []workout.Workout); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]workout.Workout)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, workout.WorkoutFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkoutRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockWorkoutRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter workout.WorkoutFilter
func (_e *MockWorkoutRepository_Expecter) List(ctx interface{}, filter interface{}) *MockWorkoutRepository_List_Call {
	return &MockWorkoutRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockWorkoutRepository_List_Call) Run(run func(ctx context.Context, filter workout.WorkoutFilter)) *MockWorkoutRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(workout.WorkoutFilter))
	})
	return _c
}

func (_c *MockWorkoutRepository_List_Call) Return(_a0 []workout.Workout, _a1 error) *MockWorkoutRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkoutRepository_List_Call) RunAndReturn(run func(context.Context, workout.WorkoutFilter) ([]workout.Workout, error)) *MockWorkoutRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// LogSet provides a mock function with given fields: ctx, workoutExerciseID, set
func (_m *MockWorkoutRepository) LogSet(ctx context.Context, workoutExerciseID uuid.UUID, set workout.WorkoutSet) (workout.WorkoutSet, error) {
	ret := _m.Called(ctx, workoutExerciseID, set)

	if len(ret) == 0 {
		panic("no return value specified for LogSet")
	}

	var r0 workout.WorkoutSet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, workout.WorkoutSet) (workout.WorkoutSet, error)); ok {
		return rf(ctx, workoutExerciseID, set)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, workout.WorkoutSet) workout.WorkoutSet); ok {
		r0 = rf(ctx, workoutExerciseID, set)
	} else {
		r0 = ret.Get(0).(workout.WorkoutSet)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, workout.WorkoutSet) error); ok {
		r1 = rf(ctx, workoutExerciseID, set)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkoutRepository_LogSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogSet'
type MockWorkoutRepository_LogSet_Call struct {
	*mock.Call
}

// LogSet is a helper method to define mock.On call
//   - ctx context.Context
//   - workoutExerciseID uuid.UUID
//   - set workout.WorkoutSet
func (_e *MockWorkoutRepository_Expecter) LogSet(ctx interface{}, workoutExerciseID interface{}, set interface{}) *MockWorkoutRepository_LogSet_Call {
	return &MockWorkoutRepository_LogSet_Call{Call: _e.mock.On("LogSet", ctx, workoutExerciseID, set)}
}

func (_c *MockWorkoutRepository_LogSet_Call) Run(run func(ctx context.Context, workoutExerciseID uuid.UUID, set workout.WorkoutSet)) *MockWorkoutRepository_LogSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(workout.WorkoutSet))
	})
	return _c
}

func (_c *MockWorkoutRepository_LogSet_Call) Return(_a0 workout.WorkoutSet, _a1 error) *MockWorkoutRepository_LogSet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkoutRepository_LogSet_Call) RunAndReturn(run func(context.Context, uuid.UUID, workout.WorkoutSet) (workout.WorkoutSet, error)) *MockWorkoutRepository_LogSet_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function with given fields: ctx, id
func (_m *MockWorkoutRepository) SoftDelete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWorkoutRepository_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type MockWorkoutRepository_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockWorkoutRepository_Expecter) SoftDelete(ctx interface{}, id interface{}) *MockWorkoutRepository_SoftDelete_Call {
	return &MockWorkoutRepository_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, id)}
}

func (_c *MockWorkoutRepository_SoftDelete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockWorkoutRepository_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockWorkoutRepository_SoftDelete_Call) Return(_a0 error) *MockWorkoutRepository_SoftDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWorkoutRepository_SoftDelete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockWorkoutRepository_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, w
func (_m *MockWorkoutRepository) Update(ctx context.Context, w workout.Workout) (workout.Workout, error) {
	ret := _m.Called(ctx, w)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 workout.Workout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, workout.Workout) (workout.Workout, error)); ok {
		return rf(ctx, w)
	}
	if rf, ok := ret.Get(0).(func(context.Context, workout.Workout) workout.Workout); ok {
		r0 = rf(ctx, w)
	} else {
		r0 = ret.Get(0).(workout.Workout)
	}

	if rf, ok := ret.Get(1).(func(context.Context, workout.Workout) error); ok {
		r1 = rf(ctx, w)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkoutRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockWorkoutRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - w workout.Workout
func (_e *MockWorkoutRepository_Expecter) Update(ctx interface{}, w interface{}) *MockWorkoutRepository_Update_Call {
	return &MockWorkoutRepository_Update_Call{Call: _e.mock.On("Update", ctx, w)}
}

func (_c *MockWorkoutRepository_Update_Call) Run(run func(ctx context.Context, w workout.Workout)) *MockWorkoutRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(workout.Workout))
	})
	return _c
}

func (_c *MockWorkoutRepository_Update_Call) Return(_a0 workout.Workout, _a1 error) *MockWorkoutRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkoutRepository_Update_Call) RunAndReturn(run func(context.Context, workout.Workout) (workout.Workout, error)) *MockWorkoutRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWorkoutRepository creates a new instance of MockWorkoutRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkoutRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkoutRepository {
	mock := &MockWorkoutRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
