// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockJWTValidator is an autogenerated mock type for the JWTValidator type
type MockJWTValidator struct {
	mock.Mock
}

type MockJWTValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJWTValidator) EXPECT() *MockJWTValidator_Expecter {
	return &MockJWTValidator_Expecter{mock: &_m.Mock}
}

// GetUserIDFromToken provides a mock function with given fields: tokenString
func (_m *MockJWTValidator) GetUserIDFromToken(tokenString string) (uuid.UUID, error) {
	ret := _m.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for GetUserIDFromToken")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (uuid.UUID, error)); ok {
		return rf(tokenString)
	}
	if rf, ok := ret.Get(0).(func(string) uuid.UUID); ok {
		r0 = rf(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJWTValidator_GetUserIDFromToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserIDFromToken'
type MockJWTValidator_GetUserIDFromToken_Call struct {
	*mock.Call
}

// GetUserIDFromToken is a helper method to define mock.On call
//   - tokenString string
func (_e *MockJWTValidator_Expecter) GetUserIDFromToken(tokenString interface{}) *MockJWTValidator_GetUserIDFromToken_Call {
	return &MockJWTValidator_GetUserIDFromToken_Call{Call: _e.mock.On("GetUserIDFromToken", tokenString)}
}

func (_c *MockJWTValidator_GetUserIDFromToken_Call) Run(run func(tokenString string)) *MockJWTValidator_GetUserIDFromToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockJWTValidator_GetUserIDFromToken_Call) Return(_a0 uuid.UUID, _a1 error) *MockJWTValidator_GetUserIDFromToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJWTValidator_GetUserIDFromToken_Call) RunAndReturn(run func(string) (uuid.UUID, error)) *MockJWTValidator_GetUserIDFromToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJWTValidator creates a new instance of MockJWTValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJWTValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJWTValidator {
	mock := &MockJWTValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
