with-expecter: true
packages:
  github.com/vladgrskkh/onerep-api/internal/service/exercise:
    config:
      dir: internal/service/exercise/mocks
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "mocks"
      filename: "{{.InterfaceName | snakecase}}.gen.go"
    interfaces:
      ExerciseRepository:
      MuscleGroupRepository:
      TransactionManager:
  github.com/vladgrskkh/onerep-api/internal/handler/exercise:
    config:
      dir: internal/handler/exercise/mocks
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "mocks"
      filename: "{{.InterfaceName | snakecase}}.gen.go"
    interfaces:
      ExerciseService:
