// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	bodyweight "github.com/vladgrskkh/onerep-api/internal/domain/bodyweight"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockBodyWeightRepository is an autogenerated mock type for the BodyWeightRepository type
type MockBodyWeightRepository struct {
	mock.Mock
}

type MockBodyWeightRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBodyWeightRepository) EXPECT() *MockBodyWeightRepository_Expecter {
	return &MockBodyWeightRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, bw
func (_m *MockBodyWeightRepository) Create(ctx context.Context, bw bodyweight.BodyWeight) (bodyweight.BodyWeight, error) {
	ret := _m.Called(ctx, bw)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 bodyweight.BodyWeight
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bodyweight.BodyWeight) (bodyweight.BodyWeight, error)); ok {
		return rf(ctx, bw)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bodyweight.BodyWeight) bodyweight.BodyWeight); ok {
		r0 = rf(ctx, bw)
	} else {
		r0 = ret.Get(0).(bodyweight.BodyWeight)
	}

	if rf, ok := ret.Get(1).(func(context.Context, bodyweight.BodyWeight) error); ok {
		r1 = rf(ctx, bw)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBodyWeightRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBodyWeightRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - bw bodyweight.BodyWeight
func (_e *MockBodyWeightRepository_Expecter) Create(ctx interface{}, bw interface{}) *MockBodyWeightRepository_Create_Call {
	return &MockBodyWeightRepository_Create_Call{Call: _e.mock.On("Create", ctx, bw)}
}

func (_c *MockBodyWeightRepository_Create_Call) Run(run func(ctx context.Context, bw bodyweight.BodyWeight)) *MockBodyWeightRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bodyweight.BodyWeight))
	})
	return _c
}

func (_c *MockBodyWeightRepository_Create_Call) Return(_a0 bodyweight.BodyWeight, _a1 error) *MockBodyWeightRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBodyWeightRepository_Create_Call) RunAndReturn(run func(context.Context, bodyweight.BodyWeight) (bodyweight.BodyWeight, error)) *MockBodyWeightRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, userID, since
func (_m *MockBodyWeightRepository) List(ctx context.Context, userID uuid.UUID, since *time.Time) ([]bodyweight.BodyWeight, error) {
	ret := _m.Called(ctx, userID, since)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []bodyweight.BodyWeight
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *time.Time) ([]bodyweight.BodyWeight, error)); ok {
		return rf(ctx, userID, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *time.Time) []bodyweight.BodyWeight); ok {
		r0 = rf(ctx, userID, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bodyweight.BodyWeight)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *time.Time) error); ok {
		r1 = rf(ctx, userID, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBodyWeightRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockBodyWeightRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - since *time.Time
func (_e *MockBodyWeightRepository_Expecter) List(ctx interface{}, userID interface{}, since interface{}) *MockBodyWeightRepository_List_Call {
	return &MockBodyWeightRepository_List_Call{Call: _e.mock.On("List", ctx, userID, since)}
}

func (_c *MockBodyWeightRepository_List_Call) Run(run func(ctx context.Context, userID uuid.UUID, since *time.Time)) *MockBodyWeightRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*time.Time))
	})
	return _c
}

func (_c *MockBodyWeightRepository_List_Call) Return(_a0 []bodyweight.BodyWeight, _a1 error) *MockBodyWeightRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBodyWeightRepository_List_Call) RunAndReturn(run func(context.Context, uuid.UUID, *time.Time) ([]bodyweight.BodyWeight, error)) *MockBodyWeightRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBodyWeightRepository creates a new instance of MockBodyWeightRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBodyWeightRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBodyWeightRepository {
	mock := &MockBodyWeightRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
