// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domaintemplate "github.com/vladgrskkh/onerep-api/internal/domain/template"

	mock "github.com/stretchr/testify/mock"

	template "github.com/vladgrskkh/onerep-api/internal/service/template"

	uuid "github.com/google/uuid"
)

// MockTemplateService is an autogenerated mock type for the TemplateService type
type MockTemplateService struct {
	mock.Mock
}

type MockTemplateService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTemplateService) EXPECT() *MockTemplateService_Expecter {
	return &MockTemplateService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, cmd
func (_m *MockTemplateService) Create(ctx context.Context, cmd template.CreateTemplateCommand) (domaintemplate.Template, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domaintemplate.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, template.CreateTemplateCommand) (domaintemplate.Template, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, template.CreateTemplateCommand) domaintemplate.Template); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Get(0).(domaintemplate.Template)
	}

	if rf, ok := ret.Get(1).(func(context.Context, template.CreateTemplateCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTemplateService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTemplateService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd template.CreateTemplateCommand
func (_e *MockTemplateService_Expecter) Create(ctx interface{}, cmd interface{}) *MockTemplateService_Create_Call {
	return &MockTemplateService_Create_Call{Call: _e.mock.On("Create", ctx, cmd)}
}

func (_c *MockTemplateService_Create_Call) Run(run func(ctx context.Context, cmd template.CreateTemplateCommand)) *MockTemplateService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(template.CreateTemplateCommand))
	})
	return _c
}

func (_c *MockTemplateService_Create_Call) Return(_a0 domaintemplate.Template, _a1 error) *MockTemplateService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTemplateService_Create_Call) RunAndReturn(run func(context.Context, template.CreateTemplateCommand) (domaintemplate.Template, error)) *MockTemplateService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Fork provides a mock function with given fields: ctx, id, userID
func (_m *MockTemplateService) Fork(ctx context.Context, id uuid.UUID, userID uuid.UUID) (domaintemplate.Template, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for Fork")
	}

	var r0 domaintemplate.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (domaintemplate.Template, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) domaintemplate.Template); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Get(0).(domaintemplate.Template)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTemplateService_Fork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fork'
type MockTemplateService_Fork_Call struct {
	*mock.Call
}

// Fork is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockTemplateService_Expecter) Fork(ctx interface{}, id interface{}, userID interface{}) *MockTemplateService_Fork_Call {
	return &MockTemplateService_Fork_Call{Call: _e.mock.On("Fork", ctx, id, userID)}
}

func (_c *MockTemplateService_Fork_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockTemplateService_Fork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockTemplateService_Fork_Call) Return(_a0 domaintemplate.Template, _a1 error) *MockTemplateService_Fork_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTemplateService_Fork_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (domaintemplate.Template, error)) *MockTemplateService_Fork_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockTemplateService) Get(ctx context.Context, id uuid.UUID) (domaintemplate.Template, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domaintemplate.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domaintemplate.Template, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) domaintemplate.Template); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domaintemplate.Template)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTemplateService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTemplateService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTemplateService_Expecter) Get(ctx interface{}, id interface{}) *MockTemplateService_Get_Call {
	return &MockTemplateService_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockTemplateService_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTemplateService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTemplateService_Get_Call) Return(_a0 domaintemplate.Template, _a1 error) *MockTemplateService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTemplateService_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (domaintemplate.Template, error)) *MockTemplateService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockTemplateService) List(ctx context.Context, filter domaintemplate.TemplateFilter) ([]domaintemplate.Template, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domaintemplate.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domaintemplate.TemplateFilter) ([]domaintemplate.Template, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domaintemplate.TemplateFilter) []domaintemplate.Template); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domaintemplate.Template)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domaintemplate.TemplateFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTemplateService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTemplateService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domaintemplate.TemplateFilter
func (_e *MockTemplateService_Expecter) List(ctx interface{}, filter interface{}) *MockTemplateService_List_Call {
	return &MockTemplateService_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockTemplateService_List_Call) Run(run func(ctx context.Context, filter domaintemplate.TemplateFilter)) *MockTemplateService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domaintemplate.TemplateFilter))
	})
	return _c
}

func (_c *MockTemplateService_List_Call) Return(_a0 []domaintemplate.Template, _a1 error) *MockTemplateService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTemplateService_List_Call) RunAndReturn(run func(context.Context, domaintemplate.TemplateFilter) ([]domaintemplate.Template, error)) *MockTemplateService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function with given fields: ctx, id, userID
func (_m *MockTemplateService) Publish(ctx context.Context, id uuid.UUID, userID uuid.UUID) (domaintemplate.Template, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 domaintemplate.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (domaintemplate.Template, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) domaintemplate.Template); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Get(0).(domaintemplate.Template)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTemplateService_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockTemplateService_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockTemplateService_Expecter) Publish(ctx interface{}, id interface{}, userID interface{}) *MockTemplateService_Publish_Call {
	return &MockTemplateService_Publish_Call{Call: _e.mock.On("Publish", ctx, id, userID)}
}

func (_c *MockTemplateService_Publish_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockTemplateService_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockTemplateService_Publish_Call) Return(_a0 domaintemplate.Template, _a1 error) *MockTemplateService_Publish_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTemplateService_Publish_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (domaintemplate.Template, error)) *MockTemplateService_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function with given fields: ctx, id, userID
func (_m *MockTemplateService) SoftDelete(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTemplateService_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type MockTemplateService_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockTemplateService_Expecter) SoftDelete(ctx interface{}, id interface{}, userID interface{}) *MockTemplateService_SoftDelete_Call {
	return &MockTemplateService_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, id, userID)}
}

func (_c *MockTemplateService_SoftDelete_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockTemplateService_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockTemplateService_SoftDelete_Call) Return(_a0 error) *MockTemplateService_SoftDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTemplateService_SoftDelete_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockTemplateService_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, cmd
func (_m *MockTemplateService) Update(ctx context.Context, cmd template.UpdateTemplateCommand) (domaintemplate.Template, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domaintemplate.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, template.UpdateTemplateCommand) (domaintemplate.Template, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, template.UpdateTemplateCommand) domaintemplate.Template); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Get(0).(domaintemplate.Template)
	}

	if rf, ok := ret.Get(1).(func(context.Context, template.UpdateTemplateCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTemplateService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTemplateService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd template.UpdateTemplateCommand
func (_e *MockTemplateService_Expecter) Update(ctx interface{}, cmd interface{}) *MockTemplateService_Update_Call {
	return &MockTemplateService_Update_Call{Call: _e.mock.On("Update", ctx, cmd)}
}

func (_c *MockTemplateService_Update_Call) Run(run func(ctx context.Context, cmd template.UpdateTemplateCommand)) *MockTemplateService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(template.UpdateTemplateCommand))
	})
	return _c
}

func (_c *MockTemplateService_Update_Call) Return(_a0 domaintemplate.Template, _a1 error) *MockTemplateService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTemplateService_Update_Call) RunAndReturn(run func(context.Context, template.UpdateTemplateCommand) (domaintemplate.Template, error)) *MockTemplateService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTemplateService creates a new instance of MockTemplateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTemplateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTemplateService {
	mock := &MockTemplateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
