// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domainworkout "github.com/vladgrskkh/onerep-api/internal/domain/workout"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"

	workout "github.com/vladgrskkh/onerep-api/internal/service/workout"
)

// MockWorkoutService is an autogenerated mock type for the WorkoutService type
type MockWorkoutService struct {
	mock.Mock
}

type MockWorkoutService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkoutService) EXPECT() *MockWorkoutService_Expecter {
	return &MockWorkoutService_Expecter{mock: &_m.Mock}
}

// AddExercise provides a mock function with given fields: ctx, cmd, userID
func (_m *MockWorkoutService) AddExercise(ctx context.Context, cmd workout.AddExerciseCommand, userID uuid.UUID) (*domainworkout.WorkoutExercise, error) {
	ret := _m.Called(ctx, cmd, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddExercise")
	}

	var r0 *domainworkout.WorkoutExercise
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, workout.AddExerciseCommand, uuid.UUID) (*domainworkout.WorkoutExercise, error)); ok {
		return rf(ctx, cmd, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, workout.AddExerciseCommand, uuid.UUID) *domainworkout.WorkoutExercise); ok {
		r0 = rf(ctx, cmd, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domainworkout.WorkoutExercise)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, workout.AddExerciseCommand, uuid.UUID) error); ok {
		r1 = rf(ctx, cmd, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkoutService_AddExercise_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddExercise'
type MockWorkoutService_AddExercise_Call struct {
	*mock.Call
}

// AddExercise is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd workout.AddExerciseCommand
//   - userID uuid.UUID
func (_e *MockWorkoutService_Expecter) AddExercise(ctx interface{}, cmd interface{}, userID interface{}) *MockWorkoutService_AddExercise_Call {
	return &MockWorkoutService_AddExercise_Call{Call: _e.mock.On("AddExercise", ctx, cmd, userID)}
}

func (_c *MockWorkoutService_AddExercise_Call) Run(run func(ctx context.Context, cmd workout.AddExerciseCommand, userID uuid.UUID)) *MockWorkoutService_AddExercise_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(workout.AddExerciseCommand), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockWorkoutService_AddExercise_Call) Return(_a0 *domainworkout.WorkoutExercise, _a1 error) *MockWorkoutService_AddExercise_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkoutService_AddExercise_Call) RunAndReturn(run func(context.Context, workout.AddExerciseCommand, uuid.UUID) (*domainworkout.WorkoutExercise, error)) *MockWorkoutService_AddExercise_Call {
	_c.Call.Return(run)
	return _c
}

// Finish provides a mock function with given fields: ctx, cmd, userID
func (_m *MockWorkoutService) Finish(ctx context.Context, cmd workout.FinishWorkoutCommand, userID uuid.UUID) (*domainworkout.Workout, error) {
	ret := _m.Called(ctx, cmd, userID)

	if len(ret) == 0 {
		panic("no return value specified for Finish")
	}

	var r0 *domainworkout.Workout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, workout.FinishWorkoutCommand, uuid.UUID) (*domainworkout.Workout, error)); ok {
		return rf(ctx, cmd, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, workout.FinishWorkoutCommand, uuid.UUID) *domainworkout.Workout); ok {
		r0 = rf(ctx, cmd, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domainworkout.Workout)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, workout.FinishWorkoutCommand, uuid.UUID) error); ok {
		r1 = rf(ctx, cmd, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkoutService_Finish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Finish'
type MockWorkoutService_Finish_Call struct {
	*mock.Call
}

// Finish is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd workout.FinishWorkoutCommand
//   - userID uuid.UUID
func (_e *MockWorkoutService_Expecter) Finish(ctx interface{}, cmd interface{}, userID interface{}) *MockWorkoutService_Finish_Call {
	return &MockWorkoutService_Finish_Call{Call: _e.mock.On("Finish", ctx, cmd, userID)}
}

func (_c *MockWorkoutService_Finish_Call) Run(run func(ctx context.Context, cmd workout.FinishWorkoutCommand, userID uuid.UUID)) *MockWorkoutService_Finish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(workout.FinishWorkoutCommand), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockWorkoutService_Finish_Call) Return(_a0 *domainworkout.Workout, _a1 error) *MockWorkoutService_Finish_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkoutService_Finish_Call) RunAndReturn(run func(context.Context, workout.FinishWorkoutCommand, uuid.UUID) (*domainworkout.Workout, error)) *MockWorkoutService_Finish_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id, userID
func (_m *MockWorkoutService) Get(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*domainworkout.Workout, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domainworkout.Workout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domainworkout.Workout, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domainworkout.Workout); ok {
		r0 = rf(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domainworkout.Workout)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkoutService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockWorkoutService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockWorkoutService_Expecter) Get(ctx interface{}, id interface{}, userID interface{}) *MockWorkoutService_Get_Call {
	return &MockWorkoutService_Get_Call{Call: _e.mock.On("Get", ctx, id, userID)}
}

func (_c *MockWorkoutService_Get_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockWorkoutService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockWorkoutService_Get_Call) Return(_a0 *domainworkout.Workout, _a1 error) *MockWorkoutService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkoutService_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*domainworkout.Workout, error)) *MockWorkoutService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetActive provides a mock function with given fields: ctx, userID
func (_m *MockWorkoutService) GetActive(ctx context.Context, userID uuid.UUID) (*domainworkout.Workout, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetActive")
	}

	var r0 *domainworkout.Workout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domainworkout.Workout, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domainworkout.Workout); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domainworkout.Workout)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkoutService_GetActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActive'
type MockWorkoutService_GetActive_Call struct {
	*mock.Call
}

// GetActive is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockWorkoutService_Expecter) GetActive(ctx interface{}, userID interface{}) *MockWorkoutService_GetActive_Call {
	return &MockWorkoutService_GetActive_Call{Call: _e.mock.On("GetActive", ctx, userID)}
}

func (_c *MockWorkoutService_GetActive_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockWorkoutService_GetActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockWorkoutService_GetActive_Call) Return(_a0 *domainworkout.Workout, _a1 error) *MockWorkoutService_GetActive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkoutService_GetActive_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domainworkout.Workout, error)) *MockWorkoutService_GetActive_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, userID, since
func (_m *MockWorkoutService) List(ctx context.Context, userID uuid.UUID, since time.Time) ([]*domainworkout.Workout, error) {
	ret := _m.Called(ctx, userID, since)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domainworkout.Workout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) ([]*domainworkout.Workout, error)); ok {
		return rf(ctx, userID, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) []*domainworkout.Workout); ok {
		r0 = rf(ctx, userID, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domainworkout.Workout)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, userID, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkoutService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockWorkoutService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - since time.Time
func (_e *MockWorkoutService_Expecter) List(ctx interface{}, userID interface{}, since interface{}) *MockWorkoutService_List_Call {
	return &MockWorkoutService_List_Call{Call: _e.mock.On("List", ctx, userID, since)}
}

func (_c *MockWorkoutService_List_Call) Run(run func(ctx context.Context, userID uuid.UUID, since time.Time)) *MockWorkoutService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockWorkoutService_List_Call) Return(_a0 []*domainworkout.Workout, _a1 error) *MockWorkoutService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkoutService_List_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) ([]*domainworkout.Workout, error)) *MockWorkoutService_List_Call {
	_c.Call.Return(run)
	return _c
}

// LogSet provides a mock function with given fields: ctx, cmd, userID
func (_m *MockWorkoutService) LogSet(ctx context.Context, cmd workout.LogSetCommand, userID uuid.UUID) (*domainworkout.SetResult, error) {
	ret := _m.Called(ctx, cmd, userID)

	if len(ret) == 0 {
		panic("no return value specified for LogSet")
	}

	var r0 *domainworkout.SetResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, workout.LogSetCommand, uuid.UUID) (*domainworkout.SetResult, error)); ok {
		return rf(ctx, cmd, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, workout.LogSetCommand, uuid.UUID) *domainworkout.SetResult); ok {
		r0 = rf(ctx, cmd, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domainworkout.SetResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, workout.LogSetCommand, uuid.UUID) error); ok {
		r1 = rf(ctx, cmd, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkoutService_LogSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogSet'
type MockWorkoutService_LogSet_Call struct {
	*mock.Call
}

// LogSet is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd workout.LogSetCommand
//   - userID uuid.UUID
func (_e *MockWorkoutService_Expecter) LogSet(ctx interface{}, cmd interface{}, userID interface{}) *MockWorkoutService_LogSet_Call {
	return &MockWorkoutService_LogSet_Call{Call: _e.mock.On("LogSet", ctx, cmd, userID)}
}

func (_c *MockWorkoutService_LogSet_Call) Run(run func(ctx context.Context, cmd workout.LogSetCommand, userID uuid.UUID)) *MockWorkoutService_LogSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(workout.LogSetCommand), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockWorkoutService_LogSet_Call) Return(_a0 *domainworkout.SetResult, _a1 error) *MockWorkoutService_LogSet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkoutService_LogSet_Call) RunAndReturn(run func(context.Context, workout.LogSetCommand, uuid.UUID) (*domainworkout.SetResult, error)) *MockWorkoutService_LogSet_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx, cmd
func (_m *MockWorkoutService) Start(ctx context.Context, cmd workout.StartWorkoutCommand) (*domainworkout.Workout, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 *domainworkout.Workout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, workout.StartWorkoutCommand) (*domainworkout.Workout, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, workout.StartWorkoutCommand) *domainworkout.Workout); ok {
		r0 = rf(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domainworkout.Workout)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, workout.StartWorkoutCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkoutService_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockWorkoutService_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd workout.StartWorkoutCommand
func (_e *MockWorkoutService_Expecter) Start(ctx interface{}, cmd interface{}) *MockWorkoutService_Start_Call {
	return &MockWorkoutService_Start_Call{Call: _e.mock.On("Start", ctx, cmd)}
}

func (_c *MockWorkoutService_Start_Call) Run(run func(ctx context.Context, cmd workout.StartWorkoutCommand)) *MockWorkoutService_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(workout.StartWorkoutCommand))
	})
	return _c
}

func (_c *MockWorkoutService_Start_Call) Return(_a0 *domainworkout.Workout, _a1 error) *MockWorkoutService_Start_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkoutService_Start_Call) RunAndReturn(run func(context.Context, workout.StartWorkoutCommand) (*domainworkout.Workout, error)) *MockWorkoutService_Start_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWorkoutService creates a new instance of MockWorkoutService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkoutService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkoutService {
	mock := &MockWorkoutService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
