// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	template "github.com/vladgrskkh/onerep-api/internal/domain/template"

	uuid "github.com/google/uuid"
)

// MockTemplateRepository is an autogenerated mock type for the TemplateRepository type
type MockTemplateRepository struct {
	mock.Mock
}

type MockTemplateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTemplateRepository) EXPECT() *MockTemplateRepository_Expecter {
	return &MockTemplateRepository_Expecter{mock: &_m.Mock}
}

// BatchInsertExercises provides a mock function with given fields: ctx, exercises
func (_m *MockTemplateRepository) BatchInsertExercises(ctx context.Context, exercises []template.TemplateExercise) error {
	ret := _m.Called(ctx, exercises)

	if len(ret) == 0 {
		panic("no return value specified for BatchInsertExercises")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []template.TemplateExercise) error); ok {
		r0 = rf(ctx, exercises)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTemplateRepository_BatchInsertExercises_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchInsertExercises'
type MockTemplateRepository_BatchInsertExercises_Call struct {
	*mock.Call
}

// BatchInsertExercises is a helper method to define mock.On call
//   - ctx context.Context
//   - exercises []template.TemplateExercise
func (_e *MockTemplateRepository_Expecter) BatchInsertExercises(ctx interface{}, exercises interface{}) *MockTemplateRepository_BatchInsertExercises_Call {
	return &MockTemplateRepository_BatchInsertExercises_Call{Call: _e.mock.On("BatchInsertExercises", ctx, exercises)}
}

func (_c *MockTemplateRepository_BatchInsertExercises_Call) Run(run func(ctx context.Context, exercises []template.TemplateExercise)) *MockTemplateRepository_BatchInsertExercises_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]template.TemplateExercise))
	})
	return _c
}

func (_c *MockTemplateRepository_BatchInsertExercises_Call) Return(_a0 error) *MockTemplateRepository_BatchInsertExercises_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTemplateRepository_BatchInsertExercises_Call) RunAndReturn(run func(context.Context, []template.TemplateExercise) error) *MockTemplateRepository_BatchInsertExercises_Call {
	_c.Call.Return(run)
	return _c
}

// BatchInsertMedia provides a mock function with given fields: ctx, media
func (_m *MockTemplateRepository) BatchInsertMedia(ctx context.Context, media []template.TemplateMedia) error {
	ret := _m.Called(ctx, media)

	if len(ret) == 0 {
		panic("no return value specified for BatchInsertMedia")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []template.TemplateMedia) error); ok {
		r0 = rf(ctx, media)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTemplateRepository_BatchInsertMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchInsertMedia'
type MockTemplateRepository_BatchInsertMedia_Call struct {
	*mock.Call
}

// BatchInsertMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - media []template.TemplateMedia
func (_e *MockTemplateRepository_Expecter) BatchInsertMedia(ctx interface{}, media interface{}) *MockTemplateRepository_BatchInsertMedia_Call {
	return &MockTemplateRepository_BatchInsertMedia_Call{Call: _e.mock.On("BatchInsertMedia", ctx, media)}
}

func (_c *MockTemplateRepository_BatchInsertMedia_Call) Run(run func(ctx context.Context, media []template.TemplateMedia)) *MockTemplateRepository_BatchInsertMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]template.TemplateMedia))
	})
	return _c
}

func (_c *MockTemplateRepository_BatchInsertMedia_Call) Return(_a0 error) *MockTemplateRepository_BatchInsertMedia_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTemplateRepository_BatchInsertMedia_Call) RunAndReturn(run func(context.Context, []template.TemplateMedia) error) *MockTemplateRepository_BatchInsertMedia_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, t
func (_m *MockTemplateRepository) Create(ctx context.Context, t template.Template) (*template.Template, error) {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *template.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, template.Template) (*template.Template, error)); ok {
		return rf(ctx, t)
	}
	if rf, ok := ret.Get(0).(func(context.Context, template.Template) *template.Template); ok {
		r0 = rf(ctx, t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*template.Template)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, template.Template) error); ok {
		r1 = rf(ctx, t)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTemplateRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTemplateRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - t template.Template
func (_e *MockTemplateRepository_Expecter) Create(ctx interface{}, t interface{}) *MockTemplateRepository_Create_Call {
	return &MockTemplateRepository_Create_Call{Call: _e.mock.On("Create", ctx, t)}
}

func (_c *MockTemplateRepository_Create_Call) Run(run func(ctx context.Context, t template.Template)) *MockTemplateRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(template.Template))
	})
	return _c
}

func (_c *MockTemplateRepository_Create_Call) Return(_a0 *template.Template, _a1 error) *MockTemplateRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTemplateRepository_Create_Call) RunAndReturn(run func(context.Context, template.Template) (*template.Template, error)) *MockTemplateRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockTemplateRepository) FindByID(ctx context.Context, id uuid.UUID) (*template.Template, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *template.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*template.Template, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *template.Template); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*template.Template)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTemplateRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockTemplateRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTemplateRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockTemplateRepository_FindByID_Call {
	return &MockTemplateRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockTemplateRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTemplateRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTemplateRepository_FindByID_Call) Return(_a0 *template.Template, _a1 error) *MockTemplateRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTemplateRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*template.Template, error)) *MockTemplateRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockTemplateRepository) List(ctx context.Context, filter template.TemplateFilter) ([]*template.Template, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*template.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, template.TemplateFilter) ([]*template.Template, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, template.TemplateFilter) []*template.Template); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*template.Template)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, template.TemplateFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTemplateRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTemplateRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter template.TemplateFilter
func (_e *MockTemplateRepository_Expecter) List(ctx interface{}, filter interface{}) *MockTemplateRepository_List_Call {
	return &MockTemplateRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockTemplateRepository_List_Call) Run(run func(ctx context.Context, filter template.TemplateFilter)) *MockTemplateRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(template.TemplateFilter))
	})
	return _c
}

func (_c *MockTemplateRepository_List_Call) Return(_a0 []*template.Template, _a1 error) *MockTemplateRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTemplateRepository_List_Call) RunAndReturn(run func(context.Context, template.TemplateFilter) ([]*template.Template, error)) *MockTemplateRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceExercises provides a mock function with given fields: ctx, templateID, exercises
func (_m *MockTemplateRepository) ReplaceExercises(ctx context.Context, templateID uuid.UUID, exercises []template.TemplateExercise) error {
	ret := _m.Called(ctx, templateID, exercises)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceExercises")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []template.TemplateExercise) error); ok {
		r0 = rf(ctx, templateID, exercises)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTemplateRepository_ReplaceExercises_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceExercises'
type MockTemplateRepository_ReplaceExercises_Call struct {
	*mock.Call
}

// ReplaceExercises is a helper method to define mock.On call
//   - ctx context.Context
//   - templateID uuid.UUID
//   - exercises []template.TemplateExercise
func (_e *MockTemplateRepository_Expecter) ReplaceExercises(ctx interface{}, templateID interface{}, exercises interface{}) *MockTemplateRepository_ReplaceExercises_Call {
	return &MockTemplateRepository_ReplaceExercises_Call{Call: _e.mock.On("ReplaceExercises", ctx, templateID, exercises)}
}

func (_c *MockTemplateRepository_ReplaceExercises_Call) Run(run func(ctx context.Context, templateID uuid.UUID, exercises []template.TemplateExercise)) *MockTemplateRepository_ReplaceExercises_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]template.TemplateExercise))
	})
	return _c
}

func (_c *MockTemplateRepository_ReplaceExercises_Call) Return(_a0 error) *MockTemplateRepository_ReplaceExercises_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTemplateRepository_ReplaceExercises_Call) RunAndReturn(run func(context.Context, uuid.UUID, []template.TemplateExercise) error) *MockTemplateRepository_ReplaceExercises_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceMedia provides a mock function with given fields: ctx, templateID, media
func (_m *MockTemplateRepository) ReplaceMedia(ctx context.Context, templateID uuid.UUID, media []template.TemplateMedia) error {
	ret := _m.Called(ctx, templateID, media)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceMedia")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []template.TemplateMedia) error); ok {
		r0 = rf(ctx, templateID, media)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTemplateRepository_ReplaceMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceMedia'
type MockTemplateRepository_ReplaceMedia_Call struct {
	*mock.Call
}

// ReplaceMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - templateID uuid.UUID
//   - media []template.TemplateMedia
func (_e *MockTemplateRepository_Expecter) ReplaceMedia(ctx interface{}, templateID interface{}, media interface{}) *MockTemplateRepository_ReplaceMedia_Call {
	return &MockTemplateRepository_ReplaceMedia_Call{Call: _e.mock.On("ReplaceMedia", ctx, templateID, media)}
}

func (_c *MockTemplateRepository_ReplaceMedia_Call) Run(run func(ctx context.Context, templateID uuid.UUID, media []template.TemplateMedia)) *MockTemplateRepository_ReplaceMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]template.TemplateMedia))
	})
	return _c
}

func (_c *MockTemplateRepository_ReplaceMedia_Call) Return(_a0 error) *MockTemplateRepository_ReplaceMedia_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTemplateRepository_ReplaceMedia_Call) RunAndReturn(run func(context.Context, uuid.UUID, []template.TemplateMedia) error) *MockTemplateRepository_ReplaceMedia_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function with given fields: ctx, id
func (_m *MockTemplateRepository) SoftDelete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTemplateRepository_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type MockTemplateRepository_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTemplateRepository_Expecter) SoftDelete(ctx interface{}, id interface{}) *MockTemplateRepository_SoftDelete_Call {
	return &MockTemplateRepository_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, id)}
}

func (_c *MockTemplateRepository_SoftDelete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTemplateRepository_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTemplateRepository_SoftDelete_Call) Return(_a0 error) *MockTemplateRepository_SoftDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTemplateRepository_SoftDelete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockTemplateRepository_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, t
func (_m *MockTemplateRepository) Update(ctx context.Context, t template.Template) (*template.Template, error) {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *template.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, template.Template) (*template.Template, error)); ok {
		return rf(ctx, t)
	}
	if rf, ok := ret.Get(0).(func(context.Context, template.Template) *template.Template); ok {
		r0 = rf(ctx, t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*template.Template)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, template.Template) error); ok {
		r1 = rf(ctx, t)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTemplateRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTemplateRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - t template.Template
func (_e *MockTemplateRepository_Expecter) Update(ctx interface{}, t interface{}) *MockTemplateRepository_Update_Call {
	return &MockTemplateRepository_Update_Call{Call: _e.mock.On("Update", ctx, t)}
}

func (_c *MockTemplateRepository_Update_Call) Run(run func(ctx context.Context, t template.Template)) *MockTemplateRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(template.Template))
	})
	return _c
}

func (_c *MockTemplateRepository_Update_Call) Return(_a0 *template.Template, _a1 error) *MockTemplateRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTemplateRepository_Update_Call) RunAndReturn(run func(context.Context, template.Template) (*template.Template, error)) *MockTemplateRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTemplateRepository creates a new instance of MockTemplateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTemplateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTemplateRepository {
	mock := &MockTemplateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
