// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockVolumeCalculator is an autogenerated mock type for the VolumeCalculator type
type MockVolumeCalculator struct {
	mock.Mock
}

type MockVolumeCalculator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVolumeCalculator) EXPECT() *MockVolumeCalculator_Expecter {
	return &MockVolumeCalculator_Expecter{mock: &_m.Mock}
}

// Recalculate provides a mock function with given fields: ctx, workoutID, userID
func (_m *MockVolumeCalculator) Recalculate(ctx context.Context, workoutID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, workoutID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Recalculate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, workoutID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVolumeCalculator_Recalculate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recalculate'
type MockVolumeCalculator_Recalculate_Call struct {
	*mock.Call
}

// Recalculate is a helper method to define mock.On call
//   - ctx context.Context
//   - workoutID uuid.UUID
//   - userID uuid.UUID
func (_e *MockVolumeCalculator_Expecter) Recalculate(ctx interface{}, workoutID interface{}, userID interface{}) *MockVolumeCalculator_Recalculate_Call {
	return &MockVolumeCalculator_Recalculate_Call{Call: _e.mock.On("Recalculate", ctx, workoutID, userID)}
}

func (_c *MockVolumeCalculator_Recalculate_Call) Run(run func(ctx context.Context, workoutID uuid.UUID, userID uuid.UUID)) *MockVolumeCalculator_Recalculate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockVolumeCalculator_Recalculate_Call) Return(_a0 error) *MockVolumeCalculator_Recalculate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVolumeCalculator_Recalculate_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockVolumeCalculator_Recalculate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVolumeCalculator creates a new instance of MockVolumeCalculator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVolumeCalculator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVolumeCalculator {
	mock := &MockVolumeCalculator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
