// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domainexercise "github.com/vladgrskkh/onerep-api/internal/domain/exercise"
	exercise "github.com/vladgrskkh/onerep-api/internal/service/exercise"

	mock "github.com/stretchr/testify/mock"
)

// MockExerciseService is an autogenerated mock type for the ExerciseService type
type MockExerciseService struct {
	mock.Mock
}

type MockExerciseService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExerciseService) EXPECT() *MockExerciseService_Expecter {
	return &MockExerciseService_Expecter{mock: &_m.Mock}
}

// UploadMedia provides a mock function with given fields: ctx, cmd
func (_m *MockExerciseService) UploadMedia(ctx context.Context, cmd exercise.UploadExerciseMediaCommand) (*domainexercise.ExerciseMedia, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for UploadMedia")
	}

	var r0 *domainexercise.ExerciseMedia
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, exercise.UploadExerciseMediaCommand) (*domainexercise.ExerciseMedia, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, exercise.UploadExerciseMediaCommand) *domainexercise.ExerciseMedia); ok {
		r0 = rf(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domainexercise.ExerciseMedia)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, exercise.UploadExerciseMediaCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExerciseService_UploadMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadMedia'
type MockExerciseService_UploadMedia_Call struct {
	*mock.Call
}

// UploadMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd exercise.UploadExerciseMediaCommand
func (_e *MockExerciseService_Expecter) UploadMedia(ctx interface{}, cmd interface{}) *MockExerciseService_UploadMedia_Call {
	return &MockExerciseService_UploadMedia_Call{Call: _e.mock.On("UploadMedia", ctx, cmd)}
}

func (_c *MockExerciseService_UploadMedia_Call) Run(run func(ctx context.Context, cmd exercise.UploadExerciseMediaCommand)) *MockExerciseService_UploadMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(exercise.UploadExerciseMediaCommand))
	})
	return _c
}

func (_c *MockExerciseService_UploadMedia_Call) Return(_a0 *domainexercise.ExerciseMedia, _a1 error) *MockExerciseService_UploadMedia_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExerciseService_UploadMedia_Call) RunAndReturn(run func(context.Context, exercise.UploadExerciseMediaCommand) (*domainexercise.ExerciseMedia, error)) *MockExerciseService_UploadMedia_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExerciseService creates a new instance of MockExerciseService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExerciseService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExerciseService {
	mock := &MockExerciseService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
