// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockObjectStorage is an autogenerated mock type for the ObjectStorage type
type MockObjectStorage struct {
	mock.Mock
}

type MockObjectStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObjectStorage) EXPECT() *MockObjectStorage_Expecter {
	return &MockObjectStorage_Expecter{mock: &_m.Mock}
}

// GenerateKey provides a mock function with given fields: prefix
func (_m *MockObjectStorage) GenerateKey(prefix string) string {
	ret := _m.Called(prefix)

	if len(ret) == 0 {
		panic("no return value specified for GenerateKey")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(prefix)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockObjectStorage_GenerateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateKey'
type MockObjectStorage_GenerateKey_Call struct {
	*mock.Call
}

// GenerateKey is a helper method to define mock.On call
//   - prefix string
func (_e *MockObjectStorage_Expecter) GenerateKey(prefix interface{}) *MockObjectStorage_GenerateKey_Call {
	return &MockObjectStorage_GenerateKey_Call{Call: _e.mock.On("GenerateKey", prefix)}
}

func (_c *MockObjectStorage_GenerateKey_Call) Run(run func(prefix string)) *MockObjectStorage_GenerateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockObjectStorage_GenerateKey_Call) Return(_a0 string) *MockObjectStorage_GenerateKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockObjectStorage_GenerateKey_Call) RunAndReturn(run func(string) string) *MockObjectStorage_GenerateKey_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: ctx, key, body, contentType
func (_m *MockObjectStorage) Upload(ctx context.Context, key string, body io.Reader, contentType string) error {
	ret := _m.Called(ctx, key, body, contentType)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, string) error); ok {
		r0 = rf(ctx, key, body, contentType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockObjectStorage_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockObjectStorage_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - body io.Reader
//   - contentType string
func (_e *MockObjectStorage_Expecter) Upload(ctx interface{}, key interface{}, body interface{}, contentType interface{}) *MockObjectStorage_Upload_Call {
	return &MockObjectStorage_Upload_Call{Call: _e.mock.On("Upload", ctx, key, body, contentType)}
}

func (_c *MockObjectStorage_Upload_Call) Run(run func(ctx context.Context, key string, body io.Reader, contentType string)) *MockObjectStorage_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader), args[3].(string))
	})
	return _c
}

func (_c *MockObjectStorage_Upload_Call) Return(_a0 error) *MockObjectStorage_Upload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockObjectStorage_Upload_Call) RunAndReturn(run func(context.Context, string, io.Reader, string) error) *MockObjectStorage_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockObjectStorage creates a new instance of MockObjectStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObjectStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObjectStorage {
	mock := &MockObjectStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
