// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	template "github.com/vladgrskkh/onerep-api/internal/service/template"
)

// MockTemplateService is an autogenerated mock type for the TemplateService type
type MockTemplateService struct {
	mock.Mock
}

type MockTemplateService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTemplateService) EXPECT() *MockTemplateService_Expecter {
	return &MockTemplateService_Expecter{mock: &_m.Mock}
}

// UploadMedia provides a mock function with given fields: ctx, cmd
func (_m *MockTemplateService) UploadMedia(ctx context.Context, cmd template.UploadTemplateMediaCommand) (*template.TemplateMediaUpload, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for UploadMedia")
	}

	var r0 *template.TemplateMediaUpload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, template.UploadTemplateMediaCommand) (*template.TemplateMediaUpload, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, template.UploadTemplateMediaCommand) *template.TemplateMediaUpload); ok {
		r0 = rf(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*template.TemplateMediaUpload)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, template.UploadTemplateMediaCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTemplateService_UploadMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadMedia'
type MockTemplateService_UploadMedia_Call struct {
	*mock.Call
}

// UploadMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd template.UploadTemplateMediaCommand
func (_e *MockTemplateService_Expecter) UploadMedia(ctx interface{}, cmd interface{}) *MockTemplateService_UploadMedia_Call {
	return &MockTemplateService_UploadMedia_Call{Call: _e.mock.On("UploadMedia", ctx, cmd)}
}

func (_c *MockTemplateService_UploadMedia_Call) Run(run func(ctx context.Context, cmd template.UploadTemplateMediaCommand)) *MockTemplateService_UploadMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(template.UploadTemplateMediaCommand))
	})
	return _c
}

func (_c *MockTemplateService_UploadMedia_Call) Return(_a0 *template.TemplateMediaUpload, _a1 error) *MockTemplateService_UploadMedia_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTemplateService_UploadMedia_Call) RunAndReturn(run func(context.Context, template.UploadTemplateMediaCommand) (*template.TemplateMediaUpload, error)) *MockTemplateService_UploadMedia_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTemplateService creates a new instance of MockTemplateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTemplateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTemplateService {
	mock := &MockTemplateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
