// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	exercise "github.com/vladgrskkh/onerep-api/internal/domain/exercise"

	uuid "github.com/google/uuid"
)

// MockExerciseRepository is an autogenerated mock type for the ExerciseRepository type
type MockExerciseRepository struct {
	mock.Mock
}

type MockExerciseRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExerciseRepository) EXPECT() *MockExerciseRepository_Expecter {
	return &MockExerciseRepository_Expecter{mock: &_m.Mock}
}

// BatchInsertMuscleGroups provides a mock function with given fields: ctx, exerciseID, groups
func (_m *MockExerciseRepository) BatchInsertMuscleGroups(ctx context.Context, exerciseID uuid.UUID, groups []exercise.ExerciseMuscleGroup) error {
	ret := _m.Called(ctx, exerciseID, groups)

	if len(ret) == 0 {
		panic("no return value specified for BatchInsertMuscleGroups")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []exercise.ExerciseMuscleGroup) error); ok {
		r0 = rf(ctx, exerciseID, groups)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExerciseRepository_BatchInsertMuscleGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchInsertMuscleGroups'
type MockExerciseRepository_BatchInsertMuscleGroups_Call struct {
	*mock.Call
}

// BatchInsertMuscleGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - exerciseID uuid.UUID
//   - groups []exercise.ExerciseMuscleGroup
func (_e *MockExerciseRepository_Expecter) BatchInsertMuscleGroups(ctx interface{}, exerciseID interface{}, groups interface{}) *MockExerciseRepository_BatchInsertMuscleGroups_Call {
	return &MockExerciseRepository_BatchInsertMuscleGroups_Call{Call: _e.mock.On("BatchInsertMuscleGroups", ctx, exerciseID, groups)}
}

func (_c *MockExerciseRepository_BatchInsertMuscleGroups_Call) Run(run func(ctx context.Context, exerciseID uuid.UUID, groups []exercise.ExerciseMuscleGroup)) *MockExerciseRepository_BatchInsertMuscleGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]exercise.ExerciseMuscleGroup))
	})
	return _c
}

func (_c *MockExerciseRepository_BatchInsertMuscleGroups_Call) Return(_a0 error) *MockExerciseRepository_BatchInsertMuscleGroups_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExerciseRepository_BatchInsertMuscleGroups_Call) RunAndReturn(run func(context.Context, uuid.UUID, []exercise.ExerciseMuscleGroup) error) *MockExerciseRepository_BatchInsertMuscleGroups_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, ex
func (_m *MockExerciseRepository) Create(ctx context.Context, ex exercise.Exercise) (exercise.Exercise, error) {
	ret := _m.Called(ctx, ex)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 exercise.Exercise
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, exercise.Exercise) (exercise.Exercise, error)); ok {
		return rf(ctx, ex)
	}
	if rf, ok := ret.Get(0).(func(context.Context, exercise.Exercise) exercise.Exercise); ok {
		r0 = rf(ctx, ex)
	} else {
		r0 = ret.Get(0).(exercise.Exercise)
	}

	if rf, ok := ret.Get(1).(func(context.Context, exercise.Exercise) error); ok {
		r1 = rf(ctx, ex)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExerciseRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockExerciseRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - ex exercise.Exercise
func (_e *MockExerciseRepository_Expecter) Create(ctx interface{}, ex interface{}) *MockExerciseRepository_Create_Call {
	return &MockExerciseRepository_Create_Call{Call: _e.mock.On("Create", ctx, ex)}
}

func (_c *MockExerciseRepository_Create_Call) Run(run func(ctx context.Context, ex exercise.Exercise)) *MockExerciseRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(exercise.Exercise))
	})
	return _c
}

func (_c *MockExerciseRepository_Create_Call) Return(_a0 exercise.Exercise, _a1 error) *MockExerciseRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExerciseRepository_Create_Call) RunAndReturn(run func(context.Context, exercise.Exercise) (exercise.Exercise, error)) *MockExerciseRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockExerciseRepository) FindByID(ctx context.Context, id uuid.UUID) (exercise.Exercise, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 exercise.Exercise
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (exercise.Exercise, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) exercise.Exercise); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(exercise.Exercise)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExerciseRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockExerciseRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockExerciseRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockExerciseRepository_FindByID_Call {
	return &MockExerciseRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockExerciseRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockExerciseRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockExerciseRepository_FindByID_Call) Return(_a0 exercise.Exercise, _a1 error) *MockExerciseRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExerciseRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (exercise.Exercise, error)) *MockExerciseRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockExerciseRepository) List(ctx context.Context, filter exercise.ExerciseFilter) ([]exercise.Exercise, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []exercise.Exercise
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, exercise.ExerciseFilter) ([]exercise.Exercise, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, exercise.ExerciseFilter) []exercise.Exercise); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]exercise.Exercise)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, exercise.ExerciseFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExerciseRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockExerciseRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter exercise.ExerciseFilter
func (_e *MockExerciseRepository_Expecter) List(ctx interface{}, filter interface{}) *MockExerciseRepository_List_Call {
	return &MockExerciseRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockExerciseRepository_List_Call) Run(run func(ctx context.Context, filter exercise.ExerciseFilter)) *MockExerciseRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(exercise.ExerciseFilter))
	})
	return _c
}

func (_c *MockExerciseRepository_List_Call) Return(_a0 []exercise.Exercise, _a1 error) *MockExerciseRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExerciseRepository_List_Call) RunAndReturn(run func(context.Context, exercise.ExerciseFilter) ([]exercise.Exercise, error)) *MockExerciseRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceMedia provides a mock function with given fields: ctx, exerciseID, media
func (_m *MockExerciseRepository) ReplaceMedia(ctx context.Context, exerciseID uuid.UUID, media []exercise.ExerciseMedia) error {
	ret := _m.Called(ctx, exerciseID, media)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceMedia")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []exercise.ExerciseMedia) error); ok {
		r0 = rf(ctx, exerciseID, media)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExerciseRepository_ReplaceMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceMedia'
type MockExerciseRepository_ReplaceMedia_Call struct {
	*mock.Call
}

// ReplaceMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - exerciseID uuid.UUID
//   - media []exercise.ExerciseMedia
func (_e *MockExerciseRepository_Expecter) ReplaceMedia(ctx interface{}, exerciseID interface{}, media interface{}) *MockExerciseRepository_ReplaceMedia_Call {
	return &MockExerciseRepository_ReplaceMedia_Call{Call: _e.mock.On("ReplaceMedia", ctx, exerciseID, media)}
}

func (_c *MockExerciseRepository_ReplaceMedia_Call) Run(run func(ctx context.Context, exerciseID uuid.UUID, media []exercise.ExerciseMedia)) *MockExerciseRepository_ReplaceMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]exercise.ExerciseMedia))
	})
	return _c
}

func (_c *MockExerciseRepository_ReplaceMedia_Call) Return(_a0 error) *MockExerciseRepository_ReplaceMedia_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExerciseRepository_ReplaceMedia_Call) RunAndReturn(run func(context.Context, uuid.UUID, []exercise.ExerciseMedia) error) *MockExerciseRepository_ReplaceMedia_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceMuscleGroups provides a mock function with given fields: ctx, exerciseID, groups
func (_m *MockExerciseRepository) ReplaceMuscleGroups(ctx context.Context, exerciseID uuid.UUID, groups []exercise.ExerciseMuscleGroup) error {
	ret := _m.Called(ctx, exerciseID, groups)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceMuscleGroups")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []exercise.ExerciseMuscleGroup) error); ok {
		r0 = rf(ctx, exerciseID, groups)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExerciseRepository_ReplaceMuscleGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceMuscleGroups'
type MockExerciseRepository_ReplaceMuscleGroups_Call struct {
	*mock.Call
}

// ReplaceMuscleGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - exerciseID uuid.UUID
//   - groups []exercise.ExerciseMuscleGroup
func (_e *MockExerciseRepository_Expecter) ReplaceMuscleGroups(ctx interface{}, exerciseID interface{}, groups interface{}) *MockExerciseRepository_ReplaceMuscleGroups_Call {
	return &MockExerciseRepository_ReplaceMuscleGroups_Call{Call: _e.mock.On("ReplaceMuscleGroups", ctx, exerciseID, groups)}
}

func (_c *MockExerciseRepository_ReplaceMuscleGroups_Call) Run(run func(ctx context.Context, exerciseID uuid.UUID, groups []exercise.ExerciseMuscleGroup)) *MockExerciseRepository_ReplaceMuscleGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]exercise.ExerciseMuscleGroup))
	})
	return _c
}

func (_c *MockExerciseRepository_ReplaceMuscleGroups_Call) Return(_a0 error) *MockExerciseRepository_ReplaceMuscleGroups_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExerciseRepository_ReplaceMuscleGroups_Call) RunAndReturn(run func(context.Context, uuid.UUID, []exercise.ExerciseMuscleGroup) error) *MockExerciseRepository_ReplaceMuscleGroups_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function with given fields: ctx, id
func (_m *MockExerciseRepository) SoftDelete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExerciseRepository_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type MockExerciseRepository_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockExerciseRepository_Expecter) SoftDelete(ctx interface{}, id interface{}) *MockExerciseRepository_SoftDelete_Call {
	return &MockExerciseRepository_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, id)}
}

func (_c *MockExerciseRepository_SoftDelete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockExerciseRepository_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockExerciseRepository_SoftDelete_Call) Return(_a0 error) *MockExerciseRepository_SoftDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExerciseRepository_SoftDelete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockExerciseRepository_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, ex
func (_m *MockExerciseRepository) Update(ctx context.Context, ex exercise.Exercise) (exercise.Exercise, error) {
	ret := _m.Called(ctx, ex)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 exercise.Exercise
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, exercise.Exercise) (exercise.Exercise, error)); ok {
		return rf(ctx, ex)
	}
	if rf, ok := ret.Get(0).(func(context.Context, exercise.Exercise) exercise.Exercise); ok {
		r0 = rf(ctx, ex)
	} else {
		r0 = ret.Get(0).(exercise.Exercise)
	}

	if rf, ok := ret.Get(1).(func(context.Context, exercise.Exercise) error); ok {
		r1 = rf(ctx, ex)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExerciseRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockExerciseRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - ex exercise.Exercise
func (_e *MockExerciseRepository_Expecter) Update(ctx interface{}, ex interface{}) *MockExerciseRepository_Update_Call {
	return &MockExerciseRepository_Update_Call{Call: _e.mock.On("Update", ctx, ex)}
}

func (_c *MockExerciseRepository_Update_Call) Run(run func(ctx context.Context, ex exercise.Exercise)) *MockExerciseRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(exercise.Exercise))
	})
	return _c
}

func (_c *MockExerciseRepository_Update_Call) Return(_a0 exercise.Exercise, _a1 error) *MockExerciseRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExerciseRepository_Update_Call) RunAndReturn(run func(context.Context, exercise.Exercise) (exercise.Exercise, error)) *MockExerciseRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExerciseRepository creates a new instance of MockExerciseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExerciseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExerciseRepository {
	mock := &MockExerciseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
