// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	exercise "github.com/vladgrskkh/onerep-api/internal/domain/exercise"
)

// MockMuscleGroupRepository is an autogenerated mock type for the MuscleGroupRepository type
type MockMuscleGroupRepository struct {
	mock.Mock
}

type MockMuscleGroupRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMuscleGroupRepository) EXPECT() *MockMuscleGroupRepository_Expecter {
	return &MockMuscleGroupRepository_Expecter{mock: &_m.Mock}
}

// List provides a mock function with given fields: ctx
func (_m *MockMuscleGroupRepository) List(ctx context.Context) ([]*exercise.MuscleGroup, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*exercise.MuscleGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*exercise.MuscleGroup, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*exercise.MuscleGroup); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*exercise.MuscleGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMuscleGroupRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockMuscleGroupRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMuscleGroupRepository_Expecter) List(ctx interface{}) *MockMuscleGroupRepository_List_Call {
	return &MockMuscleGroupRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockMuscleGroupRepository_List_Call) Run(run func(ctx context.Context)) *MockMuscleGroupRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMuscleGroupRepository_List_Call) Return(_a0 []*exercise.MuscleGroup, _a1 error) *MockMuscleGroupRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMuscleGroupRepository_List_Call) RunAndReturn(run func(context.Context) ([]*exercise.MuscleGroup, error)) *MockMuscleGroupRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMuscleGroupRepository creates a new instance of MockMuscleGroupRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMuscleGroupRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMuscleGroupRepository {
	mock := &MockMuscleGroupRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
