// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockObjectStorage is an autogenerated mock type for the ObjectStorage type
type MockObjectStorage struct {
	mock.Mock
}

type MockObjectStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObjectStorage) EXPECT() *MockObjectStorage_Expecter {
	return &MockObjectStorage_Expecter{mock: &_m.Mock}
}

// GenerateKey provides a mock function with given fields: prefix
func (_m *MockObjectStorage) GenerateKey(prefix string) string {
	ret := _m.Called(prefix)

	if len(ret) == 0 {
		panic("no return value specified for GenerateKey")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(prefix)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockObjectStorage_GenerateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateKey'
type MockObjectStorage_GenerateKey_Call struct {
	*mock.Call
}

// GenerateKey is a helper method to define mock.On call
//   - prefix string
func (_e *MockObjectStorage_Expecter) GenerateKey(prefix interface{}) *MockObjectStorage_GenerateKey_Call {
	return &MockObjectStorage_GenerateKey_Call{Call: _e.mock.On("GenerateKey", prefix)}
}

func (_c *MockObjectStorage_GenerateKey_Call) Run(run func(prefix string)) *MockObjectStorage_GenerateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockObjectStorage_GenerateKey_Call) Return(_a0 string) *MockObjectStorage_GenerateKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockObjectStorage_GenerateKey_Call) RunAndReturn(run func(string) string) *MockObjectStorage_GenerateKey_Call {
	_c.Call.Return(run)
	return _c
}

// PresignedPutURL provides a mock function with given fields: ctx, key, contentType, ttl
func (_m *MockObjectStorage) PresignedPutURL(ctx context.Context, key string, contentType string, ttl time.Duration) (string, error) {
	ret := _m.Called(ctx, key, contentType, ttl)

	if len(ret) == 0 {
		panic("no return value specified for PresignedPutURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) (string, error)); ok {
		return rf(ctx, key, contentType, ttl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) string); ok {
		r0 = rf(ctx, key, contentType, ttl)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Duration) error); ok {
		r1 = rf(ctx, key, contentType, ttl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockObjectStorage_PresignedPutURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignedPutURL'
type MockObjectStorage_PresignedPutURL_Call struct {
	*mock.Call
}

// PresignedPutURL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - contentType string
//   - ttl time.Duration
func (_e *MockObjectStorage_Expecter) PresignedPutURL(ctx interface{}, key interface{}, contentType interface{}, ttl interface{}) *MockObjectStorage_PresignedPutURL_Call {
	return &MockObjectStorage_PresignedPutURL_Call{Call: _e.mock.On("PresignedPutURL", ctx, key, contentType, ttl)}
}

func (_c *MockObjectStorage_PresignedPutURL_Call) Run(run func(ctx context.Context, key string, contentType string, ttl time.Duration)) *MockObjectStorage_PresignedPutURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockObjectStorage_PresignedPutURL_Call) Return(_a0 string, _a1 error) *MockObjectStorage_PresignedPutURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockObjectStorage_PresignedPutURL_Call) RunAndReturn(run func(context.Context, string, string, time.Duration) (string, error)) *MockObjectStorage_PresignedPutURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockObjectStorage creates a new instance of MockObjectStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObjectStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObjectStorage {
	mock := &MockObjectStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
