// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domainexercise "github.com/vladgrskkh/onerep-api/internal/domain/exercise"
	exercise "github.com/vladgrskkh/onerep-api/internal/service/exercise"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockExerciseService is an autogenerated mock type for the ExerciseService type
type MockExerciseService struct {
	mock.Mock
}

type MockExerciseService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExerciseService) EXPECT() *MockExerciseService_Expecter {
	return &MockExerciseService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, cmd
func (_m *MockExerciseService) Create(ctx context.Context, cmd exercise.CreateExerciseCommand) (*domainexercise.Exercise, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domainexercise.Exercise
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, exercise.CreateExerciseCommand) (*domainexercise.Exercise, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, exercise.CreateExerciseCommand) *domainexercise.Exercise); ok {
		r0 = rf(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domainexercise.Exercise)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, exercise.CreateExerciseCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExerciseService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockExerciseService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd exercise.CreateExerciseCommand
func (_e *MockExerciseService_Expecter) Create(ctx interface{}, cmd interface{}) *MockExerciseService_Create_Call {
	return &MockExerciseService_Create_Call{Call: _e.mock.On("Create", ctx, cmd)}
}

func (_c *MockExerciseService_Create_Call) Run(run func(ctx context.Context, cmd exercise.CreateExerciseCommand)) *MockExerciseService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(exercise.CreateExerciseCommand))
	})
	return _c
}

func (_c *MockExerciseService_Create_Call) Return(_a0 *domainexercise.Exercise, _a1 error) *MockExerciseService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExerciseService_Create_Call) RunAndReturn(run func(context.Context, exercise.CreateExerciseCommand) (*domainexercise.Exercise, error)) *MockExerciseService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockExerciseService) Get(ctx context.Context, id uuid.UUID) (*domainexercise.Exercise, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domainexercise.Exercise
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domainexercise.Exercise, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domainexercise.Exercise); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domainexercise.Exercise)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExerciseService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockExerciseService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockExerciseService_Expecter) Get(ctx interface{}, id interface{}) *MockExerciseService_Get_Call {
	return &MockExerciseService_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockExerciseService_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockExerciseService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockExerciseService_Get_Call) Return(_a0 *domainexercise.Exercise, _a1 error) *MockExerciseService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExerciseService_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domainexercise.Exercise, error)) *MockExerciseService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, cmd
func (_m *MockExerciseService) List(ctx context.Context, cmd exercise.ListExercisesCommand) ([]*domainexercise.Exercise, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domainexercise.Exercise
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, exercise.ListExercisesCommand) ([]*domainexercise.Exercise, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, exercise.ListExercisesCommand) []*domainexercise.Exercise); ok {
		r0 = rf(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domainexercise.Exercise)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, exercise.ListExercisesCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExerciseService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockExerciseService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd exercise.ListExercisesCommand
func (_e *MockExerciseService_Expecter) List(ctx interface{}, cmd interface{}) *MockExerciseService_List_Call {
	return &MockExerciseService_List_Call{Call: _e.mock.On("List", ctx, cmd)}
}

func (_c *MockExerciseService_List_Call) Run(run func(ctx context.Context, cmd exercise.ListExercisesCommand)) *MockExerciseService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(exercise.ListExercisesCommand))
	})
	return _c
}

func (_c *MockExerciseService_List_Call) Return(_a0 []*domainexercise.Exercise, _a1 error) *MockExerciseService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExerciseService_List_Call) RunAndReturn(run func(context.Context, exercise.ListExercisesCommand) ([]*domainexercise.Exercise, error)) *MockExerciseService_List_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function with given fields: ctx, id, userID
func (_m *MockExerciseService) SoftDelete(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExerciseService_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type MockExerciseService_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockExerciseService_Expecter) SoftDelete(ctx interface{}, id interface{}, userID interface{}) *MockExerciseService_SoftDelete_Call {
	return &MockExerciseService_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, id, userID)}
}

func (_c *MockExerciseService_SoftDelete_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockExerciseService_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockExerciseService_SoftDelete_Call) Return(_a0 error) *MockExerciseService_SoftDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExerciseService_SoftDelete_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockExerciseService_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, cmd
func (_m *MockExerciseService) Update(ctx context.Context, cmd exercise.UpdateExerciseCommand) (*domainexercise.Exercise, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domainexercise.Exercise
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, exercise.UpdateExerciseCommand) (*domainexercise.Exercise, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, exercise.UpdateExerciseCommand) *domainexercise.Exercise); ok {
		r0 = rf(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domainexercise.Exercise)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, exercise.UpdateExerciseCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExerciseService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockExerciseService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd exercise.UpdateExerciseCommand
func (_e *MockExerciseService_Expecter) Update(ctx interface{}, cmd interface{}) *MockExerciseService_Update_Call {
	return &MockExerciseService_Update_Call{Call: _e.mock.On("Update", ctx, cmd)}
}

func (_c *MockExerciseService_Update_Call) Run(run func(ctx context.Context, cmd exercise.UpdateExerciseCommand)) *MockExerciseService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(exercise.UpdateExerciseCommand))
	})
	return _c
}

func (_c *MockExerciseService_Update_Call) Return(_a0 *domainexercise.Exercise, _a1 error) *MockExerciseService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExerciseService_Update_Call) RunAndReturn(run func(context.Context, exercise.UpdateExerciseCommand) (*domainexercise.Exercise, error)) *MockExerciseService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExerciseService creates a new instance of MockExerciseService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExerciseService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExerciseService {
	mock := &MockExerciseService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
